name: Deploy Cron

on: workflow_dispatch
permissions:
  id-token: write
  contents: read

jobs:
  schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::742736545134:role/store-turn-github-action
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./tf/cron

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./tf/cron

      - name: Apply Terraform cron schedule
        working-directory: ./tf/cron
        run: terraform apply -auto-approve
