name: Deploy Cron

on: workflow_dispatch
permissions:
  id-token: write
  contents: read

jobs:
  schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::742736545134:role/store-turn-github-action
          aws-region: us-east-1

      - name: Initialize Terraform for cron
        run: cd ./tf/cron && terraform init

      - name: Apply Terraform cron schedule
        run: cd ./tf/cron && terraform apply -auto-approve
